### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by markons** [IBM/tnz#57]
I try to connect my TK4 session (which I can connect OK by e.g. dm3270.jar) by tnz. 
I get there following error:

Session: NONE> goto 192.168.1.71:3270
Traceback (most recent call last):
  File "C:\Users\pc\anaconda3\lib\site-packages\tnz\tnz.py", line 3689, in __connect
    await loop.create_connection(protocol, host, port,
  File "C:\Users\pc\anaconda3\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "C:\Users\pc\anaconda3\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\pc\anaconda3\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\pc\anaconda3\lib\asyncio\selector_events.py", line 500, in sock_connect
    return await fut
  File "C:\Users\pc\anaconda3\lib\asyncio\selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('192.168.1.71', 3270)
SESLOST = '192

FYI, I see for a short time the Host-window, but the connection is immediatly lost with the error above.

**Comment by najohnsn** [comment]
it might not accept secure connections. try this:
```
Session: NONE> set SESSION_SSL 0
Session: NONE> goto 92.168.1.71:3270
```

**Comment by markons** [comment]
Yes, that was it!
Thank you very much.

Regards
Gabor
