### ISSUE TITLE
termios.error: (22, 'Invalid argument')

### ISSUE THREAD

**Issue by sgonchigar** [IBM/tnz#89]
Hello, getting below error when running zti on IBMi - QSHELL Any thoughts?

  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/_termlib.py", line 135, in __init__       
    self.def_shell_mode()                                                                        
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/_termlib.py", line 59, in wrapper         
    return func(*args, **kwargs)                                                                 
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/_termlib.py", line 1084, in def_shell_mode
    cls.__shell_attr = termios.tcgetattr(termi_fd)                                               
termios.error: (22, 'Invalid argument')                                                          

During handling of the above exception, another exception occurred:                 
                                                                                    
Traceback (most recent call last):                                                  
  File "/QOpenSys/pkgs/bin/zti", line 8, in <module>                                
    sys.exit(main())                                                                
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/zti.py", line 3681, in main  
    zti.cmdloop(intro)                                                              
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/zti.py", line 196, in cmdloop
    super().cmdloop(intro=text)                                                     
      File "/QOpenSys/pkgs/lib/python3.6/cmd.py", line 138, in cmdloop                                                               
    stop = self.onecmd(line)                                                                                                     
  File "/QOpenSys/pkgs/lib/python3.6/cmd.py", line 217, in onecmd                                                                
    return func(arg)                                                                                                             
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/zti.py", line 545, in do_goto                                             
    self.__prog_mode()                                                                                                           
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/zti.py", line 1876, in __prog_mode                                        
    self.stdscr = curses.initscr()                                                                                               
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/_termlib.py", line 1275, in initscr                                       
    stdscr = Term()                                                                                                              
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/tnz/_termlib.py", line 138, in __init__                                       
    raise self.error("init failed")                                                                                              
tnz._termlib._TermlibError: init failed                                                                                          
Task was destroyed but it is pending!                                                                                            
task: <Task pending coro=<Tnz.__connect() running at /QOpenSys/pkgs/lib/python3.6/site-packages/tnz/tnz.py:3699> wait_for=<Future
 pending cb=[<TaskWakeupMethWrapper object at 0x700000000737408>()]>>

**Comment by najohnsn** [comment]
That's AIX, right? You could be the first running tnz on that platform. 

So, "Invalid Argument" is the error. Since the only argument to the function in error is the file descriptor, I guess the complaint is about that. The file descriptor comes from `sys.stdin.fileno()`. The code is already past the point where it verified that the file descriptor is a tty. So, I'm at a bit of a loss as to why the function would fail.

I'm not familiar with Qshell. But my best guess is that the "terminal environment" you are running it in (either by choice or due to the nature of Qshell) is incompatible with zti - it is not a "normal" terminal environment.

**Comment by sgonchigar** [comment]
Yes. AIX. so we were able to run successfully in batch mode in qshell/AIX using below import. 
```
from tnz.py3270 import Emulator
 em = Emulator(visible=False).
```
  Was trying to see if the interactive will work as well. I am using IBM iAccess - 5250 emulator, within that qshell/AIX. Native telnet has limitations on the screen size and your software was a big help - Thank you.

**Comment by sgonchigar** [comment]
Thank you Neil. zti works fine on windows.
